language: python
python:
   - "2.7"
services:
  - postgres
install:
  - pip install -r travis/requirements.txt
before_script:
  - psql -c 'create database mydb;' -U postgres
  - psql -f travis/test.db mydb -U postgres
script:
  - pytest