language: python
python:
   - "2.7"
services:
  - postgres
install:
  - pip install -r travis/requirements.txt
before_script:
  - psql -c 'create database mydb;' -U postgres
  - psql -c "CREATE USER searcher WITH PASSWORD '8SlpOmzM21if';" -U postgres
  - psql -f travis/test.db mydb -U postgres
  - pwd
  - cp travis/config_test.cfg config/cxDocs.cfg
script:
  - flask --version
  - pytest